<a href="https://colab.research.google.com/github/winarsibidul03/Pejuang-data-4.0/blob/main/(7)PSDS_DataFrame_dan_Numpy_Array.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#PANDAS DATAFRAME

pandas adalah library analisis data yang memiliki struktur data uang diperlukan untuk memebersihkan data mentah ke dalam sebuah bentuk yg cocok untuk analaisis yaitu tabel. 

###Import Modul

In [3]:
import pandas as pd 

## membuat dataFrame

In [ ]:
Membuat matriks menggunakan list

In [ ]:
#list
list_buah = ['Jeruk','Papaya','mangga','rambutan','leci','nanas','manggis']

# Membuat dataFrame dengan list buah
df = pd.DataFrame(list_buah)
df

0
0     Jeruk
1    Papaya
2    mangga
3  rambutan
4      leci
5     nanas
6   manggis

Membuat data frame menggunakan List dan fungsi zip

In [ ]:
# List buah(string)
List_buah = ['Jeruk','Papaya','mangga','rambutan','leci','nanas','manggis']

# List Berat Buah
List_berat = [50,800,150,10,2,300,70]

# Membuat dataFrame menggunakan dua buah list dengan fungsi zip 
df = pd.DataFrame(list(zip(List_buah,List_berat)),
                  columns = ['nama buah','berat buah'])
df

nama buah  berat buah
0     Jeruk          50
1    Papaya         800
2    mangga         150
3  rambutan          10
4      leci           2
5     nanas         300
6   manggis          70

Membuat dataFrame menggunakan list multidimensi

In [ ]:
# list multidimensi (nama,usia)
lst = [['Bejo',25],['Ari',30],
       ['Asep', 26],['Ricard',22]]
df = pd.DataFrame(lst, columns =['Nama', 'Usia'])
df

Nama  Usia
0    Bejo    25
1     Ari    30
2    Asep    26
3  Ricard    22

Import DataFrame dari file csv

## membuat dataFrame Menggunakan Dictionari

In [5]:
mobil = {'Type Mobil': ['Honda Civic','Toyota Corolla','Ford Focus','Audi A4'],
         'Harga(USD)': [22000,25000,27000,35000]
         }

df =pd.DataFrame(mobil)
df

Type Mobil  Harga(USD)
0     Honda Civic       22000
1  Toyota Corolla       25000
2      Ford Focus       27000
3         Audi A4       35000

##Import DataFrame dari File CSV

In [ ]:
df_super_store = pd.read_csv('super_store.csv')
df_super_store.head()

order_id  order_date customer_id    segment         category  \
0  CA-2016-152156   11/8/2016    CG-12520   Consumer        Furniture   
1  CA-2016-152156   11/8/2016    CG-12520   Consumer        Furniture   
2  CA-2016-138688   6/12/2016    DV-13045  Corporate  Office Supplies   
3  US-2015-108966  10/11/2015    SO-20335   Consumer        Furniture   
4  US-2015-108966  10/11/2015    SO-20335   Consumer  Office Supplies   

  sub_category     sales  quantity    profit  
0    Bookcases  261.9600         2   41.9136  
1       Chairs  731.9400         3  219.5820  
2       Labels   14.6200         2    6.8714  
3       Tables  957.5775         5 -383.0310  
4      Storage   22.3680         2    2.5164

##Import DataFrame dari file excel

In [ ]:
df_pilkada=pd.read_excel('/content/datasetpilkadadki.xlsx')
df_pilkada.head()

Id Sentiment Pasangan Calon  \
0   1  negative     Agus-Sylvi   
1   2  negative     Agus-Sylvi   
2   3  negative     Agus-Sylvi   
3   4  negative     Agus-Sylvi   
4   5  negative     Agus-Sylvi   

                                          Text Tweet  
0  Banyak akun kloning seolah2 pendukung #agussil...  
1  #agussilvy bicara apa kasihan yaa...lap itu ai...  
2  Kalau aku sih gak nunggu hasil akhir QC tp lag...  
3  Kasian oh kasian dengan peluru 1milyar untuk t...  
4  Maaf ya pendukung #AgusSilvy..hayo dukung #Ani...

## Membuat Numpy Array

In [ ]:
import numpy as np

In [ ]:
list_1 = [1,2,3,4,5]
arr_1 = np.array([list_1])
arr_1

array([[1, 2, 3, 4, 5]])

In [ ]:
print(np.zeros((2,5))) # membuat array dengan nilai 0 dengan shape (5,5)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [ ]:
print(np.ones((5,3))) # membuat array dengan nilai 1 dengan shape (5,5)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
print(np.arange(1, 10, 2)) #arange(start, stop, step)

[1 3 5 7 9]


In [ ]:
print(np.linspace(1, 10, 2)) # linespace(start, stop, number)

[ 1. 10.]


In [ ]:
print(np.logspace(1, 10, 2)) # logspace(start, stop, number)

[1.e+01 1.e+10]


In [ ]:
print(np.full((2,2), 4)) # Membuat array matriks dengan shape (2,2) dengan elemen 99

[[4 4]
 [4 4]]


In [ ]:
A = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(A)

print(np.full_like(A, 3)) # Membuat array matriks dengan shape yang sama dengan A dengan semua elemennya 4

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]
[[3 3 3 3 3 3 3]
 [3 3 3 3 3 3 3]]


In [ ]:
print(np.random.randint(-4,8, size=(3,3))) # Random Integer values

[[-2  4  0]
 [ 3 -3  0]
 [ 2  6  1]]


In [ ]:
print(np.identity(5)) # Membuat matriks identitas

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [ ]:
arr = np.array([[1,2,3]]) # Membuat matriks dengan perulangan array
r1 = np.repeat(arr,3, axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


## Metode-metode pada Array
Objek array pada Python Numpy memiliki berbagai method untuk melakukan operasi atau perintah-perintah tertentu. Berikut adalah fungsi-fungsi yang merupakan metode pada array yang sering dipakai:

**array.ndim**

Metode ini digunakan untuk mengetahui dimensi dari array.

In [ ]:
a=np.array([29, 28, 30], dtype='int32')
print(a)

print("Dimensi dari array a adalah ", a.ndim)

[29 28 30]
Dimensi dari array a adalah  1


**array.shape**

Metode ini digunakan untuk mengetahui ukuran (variabel dan baris) dari array.

In [ ]:
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

print("Ukuran Shape dari array b adalah ", b.shape)

[[9. 8. 7.]
 [6. 5. 4.]]
Ukuran Shape dari array b adalah  (2, 3)


**array.dtype**

Metode ini digunakan untuk mengetahui type data dari elemen penyusun array.

In [ ]:
a.dtype

dtype('int32')

**array.size**

Metode ini digunakan untuk menghitung jumlah elemen dari array.

In [ ]:
a.size

3

## Multidimensional Array

Salah satu fitur menarik dari NumPy adalah dia mampu membuat multidimensional array dan melakukan manipulasi array dengan mudah dan cepat

Multidimensional array adalah array yang berbentuk lebih dari 1 dimensi (1D), bisa 2D, 3D, 4D dan seterusnya

Cara membuat multidimensional array sama dengan membuat array 1 dimensi, perbedaannya hanya pada parameter yang digunakan

Berikut contohnya membuat array 2 dimensi

In [ ]:
arr_2 = np.array([[1,2,3,4,5], [2,4,6,8,10]])
arr_2

array([[ 1,  2,  3,  4,  5],
       [ 2,  4,  6,  8, 10]])

Array diatas adalah berbentuk (2,5) artinya mempunyai 2 baris dan 5 kolom

Kita bisa melihat jumlah elemen di setiap dimensi dengan menggunakan shape

In [ ]:
arr_2.shape


(2, 5)

## Indexing dan Slicing

Kita juga dapat melakukan indexing dan slicing terhadap array dengan mudah

Indexing dimulai dari 0 dan dimulai dengan notasi bracket “[ ]”

Misal kita ingin mencari nilai yang berada di index 0, 2, dan 4

In [ ]:
arr_3 = np.array([1,2,3,4,5])
print(arr_3[0])
print(arr_3[2])
print(arr_3[4])


1
3
5


In [ ]:
arr_3 = np.array([1,2,3,4,5])
print(arr_3[0:4])

[1 2 3 4]
